using System;
using System.Collections.Generic;
using System.Text;

namespace Imunizacao.Domain.Entities
{
    public class Gestacao_Item
    {
        public int? id { get; set; }
        public DateTime? dum { get; set; }
        public int? id_gestacao { get; set; }
        public DateTime? dpp { get; set; }
        public DateTime? data_nascimento { get; set; }
        public string nome { get; set; }
        public int? id_sexo { get; set; }
        public int? id_tipo_gravidez { get; set; }
        public int? id_tipo_parto { get; set; }
        public string suplementar_acido_folico { get; set; }
        public string suplementar_sulfato_ferroso { get; set; }
        public string flg_risco_habitual { get; set; }
        public string flg_alto_risco { get; set; }
        public string flg_gravidez_planejada { get; set; }
        public string flg_diabete_gestacional { get; set; }
        public string flg_infeccao_urinaria { get; set; }
        public string flg_infertilidade { get; set; }
        public string flg_dificuldade_amamentacao { get; set; }
        public string flg_cardiopatia { get; set; }
        public string flg_tromboembolismo { get; set; }
        public string flg_hipertensao_arterial { get; set; }
        public string flg_cirurgia_pelv_uterina { get; set; }
        public string flg_cirurgia { get; set; }
        public string flg_fuma { get; set; }
        public string flg_alcool { get; set; }
        public string flg_outra_droga { get; set; }
        public string flg_violencia_domestica { get; set; }
        public string flg_hiv { get; set; }
        public string flg_sifilis { get; set; }
        public string flg_toxoplasmose { get; set; }
        public string flg_anemia { get; set; }
        public string flg_incop_istmocervical { get; set; }
        public string flg_ameaca_parto_prematuro { get; set; }
        public string flg_isoimunizacao_rh { get; set; }
        public string flg_oligo { get; set; }
        public string flg_rut_premtura_menbrana { get; set; }
        public string flg_ciur { get; set; }
        public string flg_pos_datismo { get; set; }
        public string flg_febre { get; set; }
        public string flg_pre_eclampsia { get; set; }
        public string flg_uso_insulina { get; set; }
        public string flg_hemorragia_1_trimestre { get; set; }
        public string flg_hemorragia_2_trimestre { get; set; }
        public string flg_hemorragia_3_trimestre { get; set; }
        public string flg_exantema { get; set; }
        public string flg_nascido_vivo { get; set; }
        public string flg_abortou { get; set; }
        public string dsc_outro_problema { get; set; }
        public string dsc_observacao { get; set; }
        public string uuid { get; set; }
        public string nome_maternidade { get; set; }
        public int? flg_desfecho { get; set; }
        public DateTime? data_alteracao { get; set; }
        public DateTime? data_obto { get; set; }
        public int? id_maternidade { get; set; }
        public DateTime? data_referencia_maternidade { get; set; }
        public DateTime? data_cadastro { get; set; }
        public DateTime? data_inicio_prenatal { get; set; }
        public int? id_cidadao { get; set; }
        public string flg_sifilis_tratado { get; set; }
        public DateTime? data_entrou_alto_risco { get; set; }
        public int? pontos_risco { get; set; }
        public string flg_medio_risco { get; set; }
        public string flg_muito_alto_risco { get; set; }
        public string flg_instabilidade_familiar { get; set; }
        public string flg_nao_aceitacao_gravidez { get; set; }
        public string flg_risco_ocupacional { get; set; }
        public string flg_condicoes_desfavoraveis { get; set; }
        public string flg_eclampsia { get; set; }
        public string flg_placenta_previa { get; set; }
        public string flg_placenta_previa_atual { get; set; }
        public string flg_muliparidade { get; set; }
        public string flg_risco_idade { get; set; }
        public string flg_risco_altura { get; set; }
        public string flg_nao_sabe_ler { get; set; }
        public string flg_anormalidades_orgaos_rep { get; set; }
        public string flg_ameaca_aborto { get; set; }
        public string flg_anomalia_trato_gen { get; set; }
        public string flg_cancer_materno { get; set; }
        public string flg_esterilidade_tratada { get; set; }
        public string flg_neoplasia_ginecologica { get; set; }
        public string flg_malformacoes_congenitas { get; set; }
        public string flg_citologia_cervical { get; set; }
        public string flg_gravidez_gemelar { get; set; }
        public string flg_incop_istmocervical_atual { get; set; }
        public string flg_eclampsia_atual { get; set; }
        public string flg_desvio { get; set; }
        public string flg_obito_fetal { get; set; }
        public string flg_aneurismas { get; set; }
        public string flg_aterosclerose { get; set; }
        public string flg_alteracoes_osteo { get; set; }
        public string flg_cardiopatias { get; set; }
        public string flg_doencas_auto_imunes { get; set; }
        public string flg_doencas_infl_intestino { get; set; }
        public string flg_endocrinopatias { get; set; }
        public string flg_epilepsia { get; set; }
        public string flg_ginecopatia { get; set; }
        public string flg_trauma { get; set; }
        public string flg_doencas_inf_bucais { get; set; }
        public string flg_neoplasias { get; set; }
        public string flg_outras_doencas_inf { get; set; }
        public string flg_doencas_infectocontagiosas { get; set; }
        public string flg_doencas_clinicas_primarias { get; set; }
        public string flg_intervalo_interpartal { get; set; }
        public string flg_abortos { get; set; }
        public int? flg_abortos_qtde { get; set; }
        public string flg_natimorto { get; set; }
        public string flg_parto_prematuro { get; set; }
        public string flg_parto_prematuro_qtde { get; set; }
        public string flg_obitosfetais { get; set; }
        public string flg_historico_malformacao { get; set; }
        public string motivo_alto_risco { get; set; }
    }
}
