using RgCidadao.Domain.Commands.Indicadores;

namespace RgCidadao.Domain.Queries.Indicadores
{
    public class Indicador6CommandText : IIndicador6Command
    {
        public string sqlIndicador6 = $@" @select
                COUNT(P.CSI_CODPAC) AS QTDE_INDIVIDUOS,

                -- ACOMPANHADO (SISTEMA)
                -- 1 SEMESTRE
                SUM(CASE WHEN ((SELECT COUNT(DISTINCT PA.ID)
                FROM PEP_ATENDIMENTO PA
                JOIN PEP_CONDICAO_AVALIADA CA ON (CA.CSI_ID_ATEND = PA.ID) AND
                (CA.ID_CIAP IN ('K86', 'K87', 'W81') OR CA.ID_CID IN ('I10', 'I11', 'I110', 'I119',
                'I12', 'I120', 'I129', 'I13', 'I130', 'I131', 'I132', 'I139', 'I15', 'I150', 'I151',
                'I152', 'I158', 'I159', 'I270', 'I272', 'O10', 'O100', 'O101', 'O102', 'O103', 'O104', 'O109'))
                JOIN TSI_PROCENFERMAGEM PE ON PE.CSI_CODPAC = PA.ID_PACIENTE AND
                CAST(PE.CSI_DATA AS DATE) = CAST(PA.DATA AS DATE) AND
                PE.CSI_CODMED = PA.ID_MEDICO
                JOIN TSI_IPROCENFERMAGEM IPE ON IPE.CSI_CONTROLE = PE.CSI_CONTROLE AND
                IPE.CSI_CODPROC = '0301100039'
                WHERE (PA.DATA BETWEEN
                (SELECT MES_ANTERIOR FROM COMPETENCIA_ANTERIOR((SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano)), 11))
                AND (SELECT DATA_ULTIMO_DIA FROM ULTIMO_DIA((SELECT MES_ANTERIOR FROM COMPETENCIA_ANTERIOR((SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano)), 6))))) AND
                PA.ID_PACIENTE = P.CSI_CODPAC AND
                (SUBSTRING(PA.ID_CBO FROM 1 FOR 4) IN ('2251', '2252', '2253', '2231', '2235'))) > 0)
                AND
                -- 2 SEMESTRE
                ((SELECT COUNT(DISTINCT PA.ID)
                FROM PEP_ATENDIMENTO PA
                JOIN PEP_CONDICAO_AVALIADA CA ON (CA.CSI_ID_ATEND = PA.ID) AND
                (CA.ID_CIAP IN ('K86', 'K87', 'W81') OR CA.ID_CID IN ('I10', 'I11', 'I110', 'I119',
                'I12', 'I120', 'I129', 'I13', 'I130', 'I131', 'I132', 'I139', 'I15', 'I150', 'I151',
                'I152', 'I158', 'I159', 'I270', 'I272', 'O10', 'O100', 'O101', 'O102', 'O103', 'O104', 'O109'))
                JOIN TSI_PROCENFERMAGEM PE ON PE.CSI_CODPAC = PA.ID_PACIENTE AND
                CAST(PE.CSI_DATA AS DATE) = CAST(PA.DATA AS DATE) AND
                PE.CSI_CODMED = PA.ID_MEDICO
                JOIN TSI_IPROCENFERMAGEM IPE ON IPE.CSI_CONTROLE = PE.CSI_CONTROLE AND
                IPE.CSI_CODPROC = '0301100039'
                WHERE (PA.DATA BETWEEN
                (SELECT MES_ANTERIOR FROM COMPETENCIA_ANTERIOR((SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano)), 5))
                AND (SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano))) AND
                PA.ID_PACIENTE = P.CSI_CODPAC AND
                (SUBSTRING(PA.ID_CBO FROM 1 FOR 4) IN ('2251', '2252', '2253', '2231', '2235'))) > 0)
                THEN 1 ELSE 0 END) AS QTDE_ACOMPANHADO,

                -- ACOMPANHADO (VALIDO)
                -- 1 SEMESTRE
                SUM(CASE WHEN ((SELECT COUNT(DISTINCT PA.ID)
                FROM PEP_ATENDIMENTO PA
                JOIN ESUS_EXPORTACAO_ITEM EI ON EI.ID = PA.ID_ESUS_EXPORTACAO_ITEM
                JOIN ESUS_EXPORTACAO E ON E.ID = EI.ID_EXPORTACAO
                JOIN PEP_CONDICAO_AVALIADA CA ON (CA.CSI_ID_ATEND = PA.ID) AND
                (CA.ID_CIAP IN ('K86', 'K87', 'W81') OR CA.ID_CID IN ('I10', 'I11', 'I110', 'I119',
                'I12', 'I120', 'I129', 'I13', 'I130', 'I131', 'I132', 'I139', 'I15', 'I150', 'I151',
                'I152', 'I158', 'I159', 'I270', 'I272', 'O10', 'O100', 'O101', 'O102', 'O103', 'O104', 'O109'))
                JOIN TSI_PROCENFERMAGEM PE ON PE.CSI_CODPAC = PA.ID_PACIENTE AND
                CAST(PE.CSI_DATA AS DATE) = CAST(PA.DATA AS DATE) AND
                PE.CSI_CODMED = PA.ID_MEDICO
                JOIN TSI_IPROCENFERMAGEM IPE ON IPE.CSI_CONTROLE = PE.CSI_CONTROLE AND
                IPE.CSI_CODPROC = '0301100039'
                JOIN ESUS_EXPORTACAO_ITEM EI2 ON EI2.ID = IPE.ID_ESUS_EXPORTACAO_ITEM
                JOIN ESUS_EXPORTACAO E2 ON E2.ID = EI.ID_EXPORTACAO
                WHERE (PA.DATA BETWEEN
                (SELECT MES_ANTERIOR FROM COMPETENCIA_ANTERIOR((SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano)), 11))
                AND (SELECT DATA_ULTIMO_DIA FROM ULTIMO_DIA((SELECT MES_ANTERIOR FROM COMPETENCIA_ANTERIOR((SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano)), 6))))) AND
                PA.ID_PACIENTE = P.CSI_CODPAC AND
                ((P.CSI_NCARTAO IS NOT NULL AND P.CSI_NCARTAO <> '') OR
                (P.CSI_CPFPAC IS NOT NULL AND P.CSI_CPFPAC <> '')) AND
                (E.PROCESSADO_CRITICAS = 'T') AND
                ((EI.FLG_ERRO <> 'T') OR (EI.FLG_ERRO IS NULL)) AND
                (E2.PROCESSADO_CRITICAS = 'T') AND
                ((EI2.FLG_ERRO <> 'T') OR (EI2.FLG_ERRO IS NULL)) AND
                (SUBSTRING(PA.ID_CBO FROM 1 FOR 4) IN ('2251', '2252', '2253', '2231', '2235'))) > 0)
                AND
                -- 2 SEMESTRE
                ((SELECT COUNT(DISTINCT PA.ID)
                FROM PEP_ATENDIMENTO PA
                JOIN ESUS_EXPORTACAO_ITEM EI ON EI.ID = PA.ID_ESUS_EXPORTACAO_ITEM
                JOIN ESUS_EXPORTACAO E ON E.ID = EI.ID_EXPORTACAO
                JOIN PEP_CONDICAO_AVALIADA CA ON (CA.CSI_ID_ATEND = PA.ID) AND
                (CA.ID_CIAP IN ('K86', 'K87', 'W81') OR CA.ID_CID IN ('I10', 'I11', 'I110', 'I119',
                'I12', 'I120', 'I129', 'I13', 'I130', 'I131', 'I132', 'I139', 'I15', 'I150', 'I151',
                'I152', 'I158', 'I159', 'I270', 'I272', 'O10', 'O100', 'O101', 'O102', 'O103', 'O104', 'O109'))
                JOIN TSI_PROCENFERMAGEM PE ON PE.CSI_CODPAC = PA.ID_PACIENTE AND
                CAST(PE.CSI_DATA AS DATE) = CAST(PA.DATA AS DATE) AND
                PE.CSI_CODMED = PA.ID_MEDICO
                JOIN TSI_IPROCENFERMAGEM IPE ON IPE.CSI_CONTROLE = PE.CSI_CONTROLE AND
                IPE.CSI_CODPROC = '0301100039'
                JOIN ESUS_EXPORTACAO_ITEM EI2 ON EI2.ID = IPE.ID_ESUS_EXPORTACAO_ITEM
                JOIN ESUS_EXPORTACAO E2 ON E2.ID = EI.ID_EXPORTACAO
                WHERE (PA.DATA BETWEEN
                (SELECT MES_ANTERIOR FROM COMPETENCIA_ANTERIOR((SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano)), 5))
                AND (SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano))) AND
                PA.ID_PACIENTE = P.CSI_CODPAC AND
                ((P.CSI_NCARTAO IS NOT NULL AND P.CSI_NCARTAO <> '') OR
                (P.CSI_CPFPAC IS NOT NULL AND P.CSI_CPFPAC <> '')) AND
                (E.PROCESSADO_CRITICAS = 'T') AND
                ((EI.FLG_ERRO <> 'T') OR (EI.FLG_ERRO IS NULL)) AND
                (E2.PROCESSADO_CRITICAS = 'T') AND
                ((EI2.FLG_ERRO <> 'T') OR (EI2.FLG_ERRO IS NULL)) AND
                (SUBSTRING(PA.ID_CBO FROM 1 FOR 4) IN ('2251', '2252', '2253', '2231', '2235'))) > 0)
                THEN 1 ELSE 0 END) AS QTDE_ACOMPANHADO_VALIDO

            FROM TSI_CADPAC P
            JOIN ESUS_FAMILIA FAM ON FAM.ID = P.ID_FAMILIA
            JOIN VS_ESTABELECIMENTOS EST ON EST.ID = FAM.ID_DOMICILIO
            JOIN ESUS_MICROAREA MA ON MA.ID = EST.ID_MICROAREA
            JOIN ESUS_EQUIPES EQ ON EQ.ID = MA.ID_EQUIPE
            JOIN ESUS_ESTABELECIMENTO_SAUDE ES ON ES.ID = EQ.ID_ESTABELECIMENTO
            JOIN TSI_MEDICOS ME ON ME.CSI_CODMED = MA.ID_PROFISSIONAL
            WHERE P.HIPERTENSO = 'T'
            @filtros        
            @agrupamento";

        string IIndicador6Command.Indicador6 { get => sqlIndicador6; }


        public string sqlPublicoAlvo = $@" @select
                P.CSI_CODPAC AS ID_INDIVIDUO,
                P.CSI_NOMPAC AS INDIVIDUO,
                EQ.NOME_REFERENCIA AS EQUIPE,

                -- ATENDIMENTO 1 SEMESTRE (SISTEMA)
                CASE WHEN ((SELECT COUNT(DISTINCT PA.ID)
                FROM PEP_ATENDIMENTO PA
                JOIN PEP_CONDICAO_AVALIADA CA ON (CA.CSI_ID_ATEND = PA.ID) AND
                (CA.ID_CIAP IN ('K86', 'K87', 'W81') OR CA.ID_CID IN ('I10', 'I11', 'I110', 'I119',
                'I12', 'I120', 'I129', 'I13', 'I130', 'I131', 'I132', 'I139', 'I15', 'I150', 'I151',
                'I152', 'I158', 'I159', 'I270', 'I272', 'O10', 'O100', 'O101', 'O102', 'O103', 'O104', 'O109'))
                JOIN TSI_PROCENFERMAGEM PE ON PE.CSI_CODPAC = PA.ID_PACIENTE AND
                CAST(PE.CSI_DATA AS DATE) = CAST(PA.DATA AS DATE) AND
                PE.CSI_CODMED = PA.ID_MEDICO
                JOIN TSI_IPROCENFERMAGEM IPE ON IPE.CSI_CONTROLE = PE.CSI_CONTROLE AND
                IPE.CSI_CODPROC = '0301100039'
                WHERE (PA.DATA BETWEEN
                (SELECT MES_ANTERIOR FROM COMPETENCIA_ANTERIOR((SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano)), 11))
                AND (SELECT DATA_ULTIMO_DIA FROM ULTIMO_DIA((SELECT MES_ANTERIOR FROM COMPETENCIA_ANTERIOR((SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano)), 6))))) AND
                PA.ID_PACIENTE = P.CSI_CODPAC AND
                (SUBSTRING(PA.ID_CBO FROM 1 FOR 4) IN ('2251', '2252', '2253', '2231', '2235'))) > 0)
                THEN 1 ELSE 0 END AS ATD_SEMESTRE1,

                -- ATENDIMENTO 2 SEMESTRE (SISTEMA)
                CASE WHEN ((SELECT COUNT(DISTINCT PA.ID)
                FROM PEP_ATENDIMENTO PA
                JOIN PEP_CONDICAO_AVALIADA CA ON (CA.CSI_ID_ATEND = PA.ID) AND
                (CA.ID_CIAP IN ('K86', 'K87', 'W81') OR CA.ID_CID IN ('I10', 'I11', 'I110', 'I119',
                'I12', 'I120', 'I129', 'I13', 'I130', 'I131', 'I132', 'I139', 'I15', 'I150', 'I151',
                'I152', 'I158', 'I159', 'I270', 'I272', 'O10', 'O100', 'O101', 'O102', 'O103', 'O104', 'O109'))
                JOIN TSI_PROCENFERMAGEM PE ON PE.CSI_CODPAC = PA.ID_PACIENTE AND
                CAST(PE.CSI_DATA AS DATE) = CAST(PA.DATA AS DATE) AND
                PE.CSI_CODMED = PA.ID_MEDICO
                JOIN TSI_IPROCENFERMAGEM IPE ON IPE.CSI_CONTROLE = PE.CSI_CONTROLE AND
                IPE.CSI_CODPROC = '0301100039'
                WHERE (PA.DATA BETWEEN
                (SELECT MES_ANTERIOR FROM COMPETENCIA_ANTERIOR((SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano)), 5))
                AND (SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano))) AND
                PA.ID_PACIENTE = P.CSI_CODPAC AND
                (SUBSTRING(PA.ID_CBO FROM 1 FOR 4) IN ('2251', '2252', '2253', '2231', '2235'))) > 0)
                THEN 1 ELSE 0 END AS ATD_SEMESTRE2,

                -- ATENDIMENTO 1 SEMESTRE (VALIDO)
                CASE WHEN ((SELECT COUNT(DISTINCT PA.ID)
                FROM PEP_ATENDIMENTO PA
                JOIN ESUS_EXPORTACAO_ITEM EI ON EI.ID = PA.ID_ESUS_EXPORTACAO_ITEM
                JOIN ESUS_EXPORTACAO E ON E.ID = EI.ID_EXPORTACAO
                JOIN PEP_CONDICAO_AVALIADA CA ON (CA.CSI_ID_ATEND = PA.ID) AND
                (CA.ID_CIAP IN ('K86', 'K87', 'W81') OR CA.ID_CID IN ('I10', 'I11', 'I110', 'I119',
                'I12', 'I120', 'I129', 'I13', 'I130', 'I131', 'I132', 'I139', 'I15', 'I150', 'I151',
                'I152', 'I158', 'I159', 'I270', 'I272', 'O10', 'O100', 'O101', 'O102', 'O103', 'O104', 'O109'))
                JOIN TSI_PROCENFERMAGEM PE ON PE.CSI_CODPAC = PA.ID_PACIENTE AND
                CAST(PE.CSI_DATA AS DATE) = CAST(PA.DATA AS DATE) AND
                PE.CSI_CODMED = PA.ID_MEDICO
                JOIN TSI_IPROCENFERMAGEM IPE ON IPE.CSI_CONTROLE = PE.CSI_CONTROLE AND
                IPE.CSI_CODPROC = '0301100039'
                JOIN ESUS_EXPORTACAO_ITEM EI2 ON EI2.ID = IPE.ID_ESUS_EXPORTACAO_ITEM
                JOIN ESUS_EXPORTACAO E2 ON E2.ID = EI.ID_EXPORTACAO
                WHERE (PA.DATA BETWEEN
                (SELECT MES_ANTERIOR FROM COMPETENCIA_ANTERIOR((SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano)), 11))
                AND (SELECT DATA_ULTIMO_DIA FROM ULTIMO_DIA((SELECT MES_ANTERIOR FROM COMPETENCIA_ANTERIOR((SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano)), 6))))) AND
                PA.ID_PACIENTE = P.CSI_CODPAC AND
                ((P.CSI_NCARTAO IS NOT NULL AND P.CSI_NCARTAO <> '') OR
                (P.CSI_CPFPAC IS NOT NULL AND P.CSI_CPFPAC <> '')) AND
                (E.PROCESSADO_CRITICAS = 'T') AND
                ((EI.FLG_ERRO <> 'T') OR (EI.FLG_ERRO IS NULL)) AND
                (E2.PROCESSADO_CRITICAS = 'T') AND
                ((EI2.FLG_ERRO <> 'T') OR (EI2.FLG_ERRO IS NULL)) AND
                (SUBSTRING(PA.ID_CBO FROM 1 FOR 4) IN ('2251', '2252', '2253', '2231', '2235'))) > 0)
                THEN 1 ELSE 0 END AS ATD_SEMESTRE1_VALIDO,

                -- ATENDIMENTO 2 SEMESTRE (VALIDO)
                CASE WHEN ((SELECT COUNT(DISTINCT PA.ID)
                FROM PEP_ATENDIMENTO PA
                JOIN ESUS_EXPORTACAO_ITEM EI ON EI.ID = PA.ID_ESUS_EXPORTACAO_ITEM
                JOIN ESUS_EXPORTACAO E ON E.ID = EI.ID_EXPORTACAO
                JOIN PEP_CONDICAO_AVALIADA CA ON (CA.CSI_ID_ATEND = PA.ID) AND
                (CA.ID_CIAP IN ('K86', 'K87', 'W81') OR CA.ID_CID IN ('I10', 'I11', 'I110', 'I119',
                'I12', 'I120', 'I129', 'I13', 'I130', 'I131', 'I132', 'I139', 'I15', 'I150', 'I151',
                'I152', 'I158', 'I159', 'I270', 'I272', 'O10', 'O100', 'O101', 'O102', 'O103', 'O104', 'O109'))
                JOIN TSI_PROCENFERMAGEM PE ON PE.CSI_CODPAC = PA.ID_PACIENTE AND
                CAST(PE.CSI_DATA AS DATE) = CAST(PA.DATA AS DATE) AND
                PE.CSI_CODMED = PA.ID_MEDICO
                JOIN TSI_IPROCENFERMAGEM IPE ON IPE.CSI_CONTROLE = PE.CSI_CONTROLE AND
                IPE.CSI_CODPROC = '0301100039'
                JOIN ESUS_EXPORTACAO_ITEM EI2 ON EI2.ID = IPE.ID_ESUS_EXPORTACAO_ITEM
                JOIN ESUS_EXPORTACAO E2 ON E2.ID = EI.ID_EXPORTACAO
                WHERE (PA.DATA BETWEEN
                (SELECT MES_ANTERIOR FROM COMPETENCIA_ANTERIOR((SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano)), 5))
                AND (SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano))) AND
                PA.ID_PACIENTE = P.CSI_CODPAC AND
                ((P.CSI_NCARTAO IS NOT NULL AND P.CSI_NCARTAO <> '') OR
                (P.CSI_CPFPAC IS NOT NULL AND P.CSI_CPFPAC <> '')) AND
                (E.PROCESSADO_CRITICAS = 'T') AND
                ((EI.FLG_ERRO <> 'T') OR (EI.FLG_ERRO IS NULL)) AND
                (E2.PROCESSADO_CRITICAS = 'T') AND
                ((EI2.FLG_ERRO <> 'T') OR (EI2.FLG_ERRO IS NULL)) AND
                (SUBSTRING(PA.ID_CBO FROM 1 FOR 4) IN ('2251', '2252', '2253', '2231', '2235'))) > 0)
                THEN 1 ELSE 0 END AS ATD_SEMESTRE2_VALIDO

            FROM TSI_CADPAC P
            JOIN ESUS_FAMILIA FAM ON FAM.ID = P.ID_FAMILIA
            JOIN VS_ESTABELECIMENTOS EST ON EST.ID = FAM.ID_DOMICILIO
            JOIN ESUS_MICROAREA MA ON MA.ID = EST.ID_MICROAREA
            JOIN ESUS_EQUIPES EQ ON EQ.ID = MA.ID_EQUIPE
            JOIN ESUS_ESTABELECIMENTO_SAUDE ES ON ES.ID = EQ.ID_ESTABELECIMENTO
            JOIN TSI_MEDICOS ME ON ME.CSI_CODMED = MA.ID_PROFISSIONAL
            WHERE P.HIPERTENSO = 'T'
            @filtros
            ORDER BY P.CSI_NOMPAC";
        
        string IIndicador6Command.PublicoAlvo { get => sqlPublicoAlvo; }

        public string sqlCountPublicoAlvo = $@" SELECT COUNT(*) FROM (
            SELECT P.CSI_CODPAC
            FROM TSI_CADPAC P
            JOIN ESUS_FAMILIA FAM ON FAM.ID = P.ID_FAMILIA
            JOIN VS_ESTABELECIMENTOS EST ON EST.ID = FAM.ID_DOMICILIO
            JOIN ESUS_MICROAREA MA ON MA.ID = EST.ID_MICROAREA
            JOIN ESUS_EQUIPES EQ ON EQ.ID = MA.ID_EQUIPE
            JOIN ESUS_ESTABELECIMENTO_SAUDE ES ON ES.ID = EQ.ID_ESTABELECIMENTO
            JOIN TSI_MEDICOS ME ON ME.CSI_CODMED = MA.ID_PROFISSIONAL
            WHERE P.HIPERTENSO = 'T'
            @filtros)";

        string IIndicador6Command.CountPublicoAlvo { get => sqlCountPublicoAlvo; }

        public string sqlAtendimentos= $@" SELECT * FROM (
                SELECT
                PA.DATA,
                MED.CSI_NOMMED PROFISSIONAL,
                PA.ID_CBO CBO,
                CBO.DESCRICAO DESCRICAO_CBO,

                CASE WHEN ((SELECT COUNT(DISTINCT AUX1.ID)
                FROM PEP_ATENDIMENTO AUX1
                JOIN PEP_CONDICAO_AVALIADA CA ON (CA.CSI_ID_ATEND = AUX1.ID) AND
                (CA.ID_CIAP IN ('K86', 'K87', 'W81') OR CA.ID_CID IN ('I10', 'I11', 'I110', 'I119',
                'I12', 'I120', 'I129', 'I13', 'I130', 'I131', 'I132', 'I139', 'I15', 'I150', 'I151',
                'I152', 'I158', 'I159', 'I270', 'I272', 'O10', 'O100', 'O101', 'O102', 'O103', 'O104', 'O109'))
                JOIN TSI_PROCENFERMAGEM PE ON PE.CSI_CODPAC = AUX1.ID_PACIENTE AND
                CAST(PE.CSI_DATA AS DATE) = CAST(AUX1.DATA AS DATE) AND
                PE.CSI_CODMED = AUX1.ID_MEDICO
                JOIN TSI_IPROCENFERMAGEM IPE ON IPE.CSI_CONTROLE = PE.CSI_CONTROLE AND
                IPE.CSI_CODPROC = '0301100039'
                WHERE AUX1.ID = PA.ID AND
                (SUBSTRING(AUX1.ID_CBO FROM 1 FOR 4) IN ('2251', '2252', '2253', '2231', '2235'))) > 0)
                THEN 'ATENDIMENTO INDIVIDUAL COM AFERIÇÃO DE P.A' ELSE 'ATENDIMENTO INDIVIDUAL' END AS PROCEDIMENTO,

                COALESCE((SELECT 'CIAP: '||LIST(COALESCE(CA.ID_CIAP, '')) || ' | ' || 'CID: '||LIST(COALESCE(CA.ID_CID, ''))
                FROM PEP_CONDICAO_AVALIADA CA WHERE CA.CSI_ID_ATEND = PA.ID AND (CA.ID_CIAP IS NOT NULL OR CA.ID_CID IS NOT NULL)), '--') AS CONDICAO_AVALIADA,

                EQ.DSC_AREA EQUIPE,
                U.CSI_NOMUNI UNIDADE_SAUDE,

                CASE WHEN (COALESCE(E.PROCESSADO_CRITICAS, 'F') = 'T') THEN 1 ELSE 0 END AS PROCESSADO_CRITICAS,
                CASE WHEN (COALESCE(EI.FLG_ERRO, 'F') = 'T') THEN 1 ELSE 0 END AS FLG_ERRO,

                CASE WHEN (E.ID IS NULL) THEN 'Registro não exportado'
                WHEN (COALESCE(E.PROCESSADO_CRITICAS, 'F') = 'T') THEN EI.DESCRICAO_ERRO
                ELSE 'Arquivo de críticas não processado'
                END AS DESCRICAO_ERRO,

                CASE WHEN (CAST(EXTRACT(MONTH FROM PA.DATA) AS INTEGER) <= 6)
                THEN '1' ELSE '2' END AS SEMESTRE,

                CASE WHEN (SUBSTRING(PA.ID_CBO FROM 1 FOR 4) IN ('2251', '2252', '2253', '2231', '2235'))
                THEN 1 ELSE 0 END AS CBO_VALIDO,

                CASE WHEN ((SELECT COUNT(DISTINCT AUX1.ID) FROM PEP_ATENDIMENTO AUX1
                JOIN PEP_CONDICAO_AVALIADA CA ON (CA.CSI_ID_ATEND = AUX1.ID) AND
                (CA.ID_CIAP IN ('K86', 'K87', 'W81') OR CA.ID_CID IN ('I10', 'I11', 'I110', 'I119',
                'I12', 'I120', 'I129', 'I13', 'I130', 'I131', 'I132', 'I139', 'I15', 'I150', 'I151',
                'I152', 'I158', 'I159', 'I270', 'I272', 'O10', 'O100', 'O101', 'O102', 'O103', 'O104', 'O109'))
                WHERE AUX1.ID = PA.ID) > 0) THEN 1 ELSE 0 END AS CID_CIAP_VALIDO,

                -- INDICADOR (SISTEMA)
                CASE WHEN ((SELECT COUNT(DISTINCT AUX1.ID)
                FROM PEP_ATENDIMENTO AUX1
                JOIN PEP_CONDICAO_AVALIADA CA ON (CA.CSI_ID_ATEND = AUX1.ID) AND
                (CA.ID_CIAP IN ('K86', 'K87', 'W81') OR CA.ID_CID IN ('I10', 'I11', 'I110', 'I119',
                'I12', 'I120', 'I129', 'I13', 'I130', 'I131', 'I132', 'I139', 'I15', 'I150', 'I151',
                'I152', 'I158', 'I159', 'I270', 'I272', 'O10', 'O100', 'O101', 'O102', 'O103', 'O104', 'O109'))
                JOIN TSI_PROCENFERMAGEM PE ON PE.CSI_CODPAC = AUX1.ID_PACIENTE AND
                CAST(PE.CSI_DATA AS DATE) = CAST(AUX1.DATA AS DATE) AND
                PE.CSI_CODMED = AUX1.ID_MEDICO
                JOIN TSI_IPROCENFERMAGEM IPE ON IPE.CSI_CONTROLE = PE.CSI_CONTROLE AND
                IPE.CSI_CODPROC = '0301100039'
                WHERE AUX1.ID = PA.ID AND
                (SUBSTRING(AUX1.ID_CBO FROM 1 FOR 4) IN ('2251', '2252', '2253', '2231', '2235'))) > 0)
                THEN 1 ELSE 0 END AS INDICADOR,

                -- INDICADOR (VALIDO)
                CASE WHEN ((SELECT COUNT(DISTINCT AUX1.ID)
                FROM PEP_ATENDIMENTO AUX1
                JOIN ESUS_EXPORTACAO_ITEM EI ON EI.ID = AUX1.ID_ESUS_EXPORTACAO_ITEM
                JOIN ESUS_EXPORTACAO E ON E.ID = EI.ID_EXPORTACAO
                JOIN PEP_CONDICAO_AVALIADA CA ON (CA.CSI_ID_ATEND = AUX1.ID) AND
                (CA.ID_CIAP IN ('K86', 'K87', 'W81') OR CA.ID_CID IN ('I10', 'I11', 'I110', 'I119',
                'I12', 'I120', 'I129', 'I13', 'I130', 'I131', 'I132', 'I139', 'I15', 'I150', 'I151',
                'I152', 'I158', 'I159', 'I270', 'I272', 'O10', 'O100', 'O101', 'O102', 'O103', 'O104', 'O109'))
                JOIN TSI_PROCENFERMAGEM PE ON PE.CSI_CODPAC = AUX1.ID_PACIENTE AND
                CAST(PE.CSI_DATA AS DATE) = CAST(AUX1.DATA AS DATE) AND
                PE.CSI_CODMED = AUX1.ID_MEDICO
                JOIN TSI_IPROCENFERMAGEM IPE ON IPE.CSI_CONTROLE = PE.CSI_CONTROLE AND
                IPE.CSI_CODPROC = '0301100039'
                JOIN ESUS_EXPORTACAO_ITEM EI2 ON EI2.ID = IPE.ID_ESUS_EXPORTACAO_ITEM
                JOIN ESUS_EXPORTACAO E2 ON E2.ID = EI.ID_EXPORTACAO
                WHERE AUX1.ID = PA.ID AND
                (E.PROCESSADO_CRITICAS = 'T') AND
                ((EI.FLG_ERRO <> 'T') OR (EI.FLG_ERRO IS NULL)) AND
                (E2.PROCESSADO_CRITICAS = 'T') AND
                ((EI2.FLG_ERRO <> 'T') OR (EI2.FLG_ERRO IS NULL)) AND
                (SUBSTRING(AUX1.ID_CBO FROM 1 FOR 4) IN ('2251', '2252', '2253', '2231', '2235'))) > 0)
                THEN 1 ELSE 0 END AS INDICADOR_VALIDO,
                E.LOTE AS LOTE

            FROM PEP_ATENDIMENTO PA
            JOIN TSI_MEDICOS MED ON (PA.ID_MEDICO = MED.CSI_CODMED)
            JOIN TSI_CBO CBO ON (PA.ID_CBO = CBO.CODIGO)
            LEFT JOIN ESUS_EQUIPES EQ ON EQ.ID = PA.ID_EQUIPE
            LEFT JOIN TSI_UNIDADE U ON PA.ID_UNIDADE = U.CSI_CODUNI
            LEFT JOIN ESUS_EXPORTACAO_ITEM EI ON EI.ID = PA.ID_ESUS_EXPORTACAO_ITEM
            LEFT JOIN ESUS_EXPORTACAO E ON E.ID = EI.ID_EXPORTACAO
            WHERE (PA.DATA BETWEEN
            (SELECT MES_ANTERIOR FROM COMPETENCIA_ANTERIOR((SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano)), 11))
            AND (SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(@quadrimestre, @ano))) AND
            PA.ID_PACIENTE = @id_individuo

            UNION ALL

            SELECT
                PE.CSI_DATA DATA,
                MED.CSI_NOMMED PROFISSIONAL,
                PE.CSI_CBO,
                CBO.DESCRICAO DESCRICAO_CBO,
                PROC.NOME PROCEDIMENTO,
                '--' AS CONDICAO_AVALIADA,
                EQ.DSC_AREA EQUIPE,
                U.CSI_NOMUNI UNIDADE_SAUDE,
                CASE WHEN (COALESCE(E.PROCESSADO_CRITICAS, 'F') = 'T') THEN 1 ELSE 0 END AS PROCESSADO_CRITICAS,
                CASE WHEN (COALESCE(EI.FLG_ERRO, 'F') = 'T') THEN 1 ELSE 0 END AS FLG_ERRO,

                CASE WHEN (E.ID IS NULL) THEN 'Registro não exportado'
                WHEN (COALESCE(E.PROCESSADO_CRITICAS, 'F') = 'T') THEN EI.DESCRICAO_ERRO
                ELSE 'Arquivo de críticas não processado'
                END AS DESCRICAO_ERRO,

                CASE WHEN (CAST(EXTRACT(MONTH FROM PE.CSI_DATA) AS INTEGER) <= 6)
                THEN '1' ELSE '2' END AS SEMESTRE,

                CASE WHEN (SUBSTRING(PE.CSI_CBO FROM 1 FOR 4) IN ('2251', '2252', '2253', '2231', '2235', '3222'))
                THEN 1 ELSE 0 END AS CBO_VALIDO,

                0 AS CID_CIAP_VALIDO,
                0 AS INDICADOR,
                0 AS INDICADOR_VALIDO,
                E.LOTE AS LOTE

            FROM TSI_PROCENFERMAGEM PE
            JOIN TSI_IPROCENFERMAGEM IPE ON IPE.CSI_CONTROLE = PE.CSI_CONTROLE
            LEFT JOIN PEP_ATENDIMENTO PA ON (PA.ID_PACIENTE = PE.CSI_CODPAC AND
            CAST(PA.DATA AS DATE) = CAST(PE.CSI_DATA AS DATE) AND PA.ID_MEDICO = PE.CSI_CODMED)
            JOIN TSI_PROCEDIMENTO PROC ON (IPE.CSI_CODPROC = PROC.CODIGO)
            JOIN TSI_MEDICOS MED ON (PE.CSI_CODMED = MED.CSI_CODMED)
            JOIN TSI_CBO CBO ON (PE.CSI_CBO = CBO.CODIGO)
            LEFT JOIN ESUS_EQUIPES EQ ON (PE.ID_EQUIPE = EQ.ID)
            JOIN TSI_UNIDADE U ON (PE.CSI_CODUNI = U.CSI_CODUNI)
            LEFT JOIN ESUS_EXPORTACAO_ITEM EI ON EI.ID = IPE.ID_ESUS_EXPORTACAO_ITEM
            LEFT JOIN ESUS_EXPORTACAO E ON E.ID = EI.ID_EXPORTACAO
            WHERE (PE.CSI_CODPAC = @id_individuo) AND
            (PE.CSI_DATA BETWEEN
            (SELECT MES_ANTERIOR FROM COMPETENCIA_ANTERIOR((SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(NULL, @ano)), 11))
            AND (SELECT DATA FROM FECHAMENTO_QUADRIMESTRE(NULL, @ano))) AND
            (IPE.CSI_CODPROC IN ('0301100039')) AND PA.ID IS NULL)
            ORDER BY DATA";

        string IIndicador6Command.Atendimentos { get => sqlAtendimentos; }
    }
}
